# Generated by Django 4.1.6 on 2023-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_blogs_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
